### ISSUE TITLE
modules.logs.mod_logs not loading

### ISSUE THREAD

**Issue by RGBCube** [Clutter-Development/Clutter#1]
```
Couldn't load mod_logs:
   ╭──────────────────╯
   │Traceback (most recent call last):
   │  File "/home/asus/PyProjects/Clutter/venv/lib/python3.10/site-packages/discord/ext/commands/bot.py", line 606, in _load_from_module_spec
   │    spec.loader.exec_module(lib)
   │  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
   │  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
   │  File "/home/asus/PyProjects/Clutter/modules/logs/mod_logs.py", line 7, in <module>
   │    class ModLogs(commands.Cog):
   │  File "/home/asus/PyProjects/Clutter/modules/logs/mod_logs.py", line 21, in ModLogs
   │    async def on_modlog(self, event: ModEvent):
   │  File "/home/asus/PyProjects/Clutter/venv/lib/python3.10/site-packages/discord/ext/commands/cog.py", line 278, in listener
   │    raise TypeError('Cog.listener expected str but received {0.__class__.__name__!r} instead.'.format(name))
   │TypeError: Cog.listener expected str but received 'function' instead.
   │
   │The above exception was the direct cause of the following exception:
   │
   │Traceback (most recent call last):
   │  File "/home/asus/PyProjects/Clutter/main.py", line 20, in <module>
   │    bot.load_extension(file_path)
   │  File "/home/asus/PyProjects/Clutter/venv/lib/python3.10/site-packages/discord/ext/commands/bot.py", line 678, in load_extension
   │    self._load_from_module_spec(spec, name)
   │  File "/home/asus/PyProjects/Clutter/venv/lib/python3.10/site-packages/discord/ext/commands/bot.py", line 609, in _load_from_module_spec
   │    raise errors.ExtensionFailed(key, e) from e
   │discord.ext.commands.errors.ExtensionFailed: Extension 'modules.logs.mod_logs' raised an error: TypeError: Cog.listener expected str but received 'function' instead.
```

**Comment by RGBCube** [comment]
this might be because its a listener, will try it out soon
